[package]
name = "rust_os"
version = "0.1.0"
authors = ["Rehket <aalbright425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
